name: therma_sim
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - cython
  - numba
  - jupyter
  - notebook
  - ipywidgets
  - geopandas
  - fiona
  - rasterio
  - shapely
  - pip:
      - mesa
      - mesa-viz-tornado
      - thermanewt==0.0.1
      - thermasim==0.0.1
      - pyspark
      - solara
      - cookiecutter
      - pytest
      - pytest-pythonpath
      - rich
      - polars
      - duckdb
      - pyyaml
